version: '{build}-{branch}'

environment:
  matrix:
    - PYTHON: "C:\\Python27"

#cache:
#  - '%PYTHON%\Lib\site-packages'

install:
  # - ps: Start-FileDownload "https://github.com/appveyor/ci/raw/master/scripts/enable-rdp.ps1" -Timeout 60000
  # - enable-rdp.ps1

  # HTML Help Workshop 1.32
  # - cinst html-help-workshop

  # Microsoft Visual C++ Redistributable 2008 (version min: 9.0.21022.8)
  # - cinst vcredist2008


  # --------------PowerShell Downloads--------------

  # InnoSetup
  - ps: Start-FileDownload "http://www.innosetup.com/download.php/is-unicode.exe" -Timeout 60000 -FileName "is-unicode.exe"

  # Stackless Python 2.7.9 x32
  - ps: Start-FileDownload "http://www.stackless.com/binaries/python-2.7.12150-stackless.msi" -Timeout 60000 -FileName "stackless-setup.msi"

  # wxPython 3.0.2
  - ps: Start-FileDownload "http://downloads.sourceforge.net/wxpython/wxPython3.0-win32-3.0.2.0-py27.exe" -Timeout 60000 -FileName "wxPython3.0-win32-3.0.2.0-py27.exe"

  # Subversion
  - ps: Start-FileDownload "https://sourceforge.net/projects/win32svn/files/1.8.17/Setup-Subversion-1.8.17.msi/download" -Timeout 60000 -FileName "Setup-Subversion-1.8.17.msi"

  # PyWin32
  - ps: Start-FileDownload "https://sourceforge.net/projects/pywin32/files/pywin32/Build%20220/pywin32-220.win32-py2.7.exe/download" -Timeout 60000 -FileName "pywin32-220.win32-py2.7.exe"


  # --------------PowerShell Installs---------------

  # InnoSetup
  - is-unicode.exe /SP /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /RESTARTAPPLICATIONS /NOICONS

  # Stackless Python 2.7.9 x32
  - stackless-setup.msi /quiet /passive /qn /norestart

  # wxPython 3.0.2
  - wxPython3.0-win32-3.0.2.0-py27.exe /VERYSILENT /SUPPRESSMSGBOXES

  # Subversion
  - Setup-Subversion-1.8.17.msi /quiet /passive /qn /norestart


  # --------------Environment Settings--------------

  # Subversion **NOTE this is need to have ctypeslib install properly
  - set PATH=%PATH%;C:\Program Files (x86)\Subversion\bin


  # -----------------Python PIP---------------------

  # SetupTools/Easy_Install Upgrade
  - pip install --upgrade setuptools

  # Module Installations **NOTE jinja has to be version < 2.9 due to error in an async module
  - pip install jinja2==2.8.1
  - pip install commonmark==0.7.2
  - pip install sphinx==1.4.8
  - pip install pillow==3.4.2
  - pip install py2exe_py2==0.6.9


  # --------------Python Easy_Install---------------

  # Module Installations
  - easy_install comtypes
  - easy_install http://svn.python.org/projects/ctypes/trunk/ctypeslib/#egg=ctypeslib-dev
  - easy_install pycrypto
  - easy_install pywin32-220.win32-py2.7.exe


  # ------------PyWin32 Post Install----------------

  - python C:\Python27\Scripts\pywin32_postinstall.py -install


# ---------------Start Build Process----------------

build: off

after_test:
  - "python.exe _build\\Build.py --build --package"
  # - dir _build\output\*.exe /B > setup-exe.txt
  # - set /P setup-exe= < setup-exe.txt
  # - START /WAIT %setup-exe% /VERYSILENT /SUPPRESSMSGBOXES /NOCLOSEAPPLICATIONS

artifacts:
  - path: "_build\\output\\*Setup.exe"
