# In AppVeyor's web config add an enviremont variable named GITHUB_TOKEN.
# Set it to a token you've created on GitHub.
# To draft a release on GitHub with AppVeyor, create a tag on master.


version: '{build}-{branch}'


#init:
#  # Enable Remotedesktop and pause the build execution
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


environment:
  PYTHON: 'C:\Stackless27'
  PYTHONPATH: 'C:\Stackless27;C:\Stackless27\Scripts;C:\Stackless27\DLLs;C:\Stackless27\Lib;C:\Stackless27\Lib\site-packages;'


matrix:
  fast_finish: true


cache:
  # Invalidate cache if .appveyor.yml has changed
  - C:\Stackless27 -> .appveyor.yml
  # Manually clear cache:
  # from agithub.AppVeyor import AppVeyor
  # ci = AppVeyor(<your appveyor API token>)
  # status, data = ci.api.projects.<appveyor username>.<appveyor projectname>.buildcache.delete()
  # print status  # 204 = Ok, cache deleted


install:
  # HTML Help Workshop 1.32
  # - cinst html-help-workshop

  # Microsoft Visual C++ Redistributable 2008 (version min: 9.0.21022.8)
  # - cinst vcredist2008

  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: |
      $Env:PATH = $Env:PATH -replace "Python27", "Stackless27"
      $PythonFolder = $Env:PYTHON
      $PythonScripts = $PythonFolder + "\Scripts"
      $SitePackages = $PythonFolder + "\lib\site-packages"
      $SysWOW = $Env:SYSTEMROOT + "\SysWOW64"
      $PythonWindowsDLL = $SysWOW + "\python27.dll"
      $PythonDLL = $PythonFolder + "\python27.dll"
      $InstallersFolder = $Env:APPVEYOR_BUILD_FOLDER + "\_build\installers\"

      Remove-Item $PythonWindowsDLL
      New-Item $InstallersFolder -type directory | Out-Null
      " "
      "=============== prepare EventGhost build environment ==============="
      If (-not (Test-Path $PythonFolder))
      {

        $pip_install = {
          Param ([string]$msg, [string]$mod, [string]$script_dir)

          Wait-Job -Name "InstallPython" -Timeout 300
          Wait-Job -Name "UpdateModuleInstallers" -Timeout 300
          Wait-Job -Name "JinjaInstall" -Timeout 300

          Write-Host " "
          Write-Host "--- " + $msg
          Write-Host "    Installing..."

          Start-Process -FilePath $script_dir + "\pip.exe"  -Arg "install -q " + $mod -Wait -WindowStyle Hidden
          Write-Host "    Done."
        }

        $python_install = {
          Param ([string]$python_dir, [string]$installers_folder)

          Write-Host " "
          Write-Host "--- Stackless 2.7.12150 x86"
          $StacklessInstaller = $installers_folder + "python-2.7.12150-stackless.msi"
          $StacklessInstallDir = "TARGETDIR=" + $python_dir
          $StacklessURL = "http://www.stackless.com/binaries/python-2.7.12150-stackless.msi"
          Start-FileDownload $StacklessURL -Timeout 60000 -FileName $StacklessInstaller
          Write-Host "    Installing..."
          Start-Process MsiExec.exe -Arg "/I $StacklessInstaller /quiet /passive /qn /norestart $StacklessInstallDir" -Wait
          Write-Host "    Done."
          Write-Host " "
        }

        $wx_install = {
          Param ([string]$installers_folder)

          $WXInstaller = $installers_folder + "wxPython3.0-win32-3.0.2.0-py27.exe"
          $WXURL = "http://downloads.sourceforge.net/wxpython/wxPython3.0-win32-3.0.2.0-py27.exe"
          Write-Host "--- wxPython 3.0.2.0"
          Start-FileDownload $WXURL -Timeout 60000 -FileName $WXInstaller
          Wait-Job -Name "InstallPython" -Timeout 300
          Write-Host "    Installing..."
          Start-Process $WXInstaller -Arg "/VERYSILENT /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          Write-Host "    Done."
        }


        $mod_updates = {
          Param ([string]$python_dir)

          Wait-Job -Name "InstallPython" -Timeout 300
          Write-Host " "
          Write-Host "--- pip 9.0.1"
          Write-Host "    Updating..."
          Start-Process -FilePath $python_dir + "\python.exe" -Arg "-m pip install -q -U pip==9.0.1" -Wait -WindowStyle Hidden
          Write-Host "    Done."
          Write-Host " "
          Write-Host "--- setuptools 34.3.0"
          Write-Host "    Updating..."
          Start-Process -FilePath $python_dir + "\Scripts\pip.exe" -Arg "install -q -U setuptools==34.3.0" -Wait -WindowStyle Hidden
          Write-Host "    Done."
        }

        $jinja_install = {
          Param ([string]$script_dir)

          Wait-Job -Name "InstallPython" -Timeout 300
          Wait-Job -Name "UpdateModuleInstallers" -Timeout 300
          Write-Host " "
          Write-Host "--- jinja2 2.8.1"
          Write-Host "    Installing..."
          Write-Host Start-Process -FilePath $script_dir + "\pip.exe" -Arg "install -q jinja2==2.8.1" -Wait -WindowStyle Hidden
          Write-Host "    Done."
        }

        $job1 = Start-Job -Name "InstallPython" -ScriptBlock $python_install -Arg "-python_dir $PythonFolder -installers_folder $InstallersFolder"
        $job2 = Start-Job -Name "InstallWX" -ScriptBlock $wx_install -Arg "-installers_folder $InstallersFolder"
        $job3 = Start-Job -Name "UpdateModuleInstallers" -ScriptBlock $mod_updates -Arg "-python_dir $PythonFolder"
        $job4 = Start-Job -Name "JinjaInstall" -ScriptBlock $jinja_install -Arg "-script_dir $PythonScripts"
        $job5 = Start-Job -ScriptBlock $pip_install -Arg '-msg "wheel 0.29.0" -mod "heel==0.29.0" -script_dir $PythonScripts'
        $job6 = Start-Job -ScriptBlock $pip_install -Arg '-msg "sphinx 1.5.6" -mod "sphinx==1.5.6" -script_dir $PythonScripts'
        $job7 = Start-Job -ScriptBlock $pip_install -Arg '-msg "pillow 3.4.2" -mod "pillow==3.4.2" -script_dir $PythonScripts'
        $job8 = Start-Job -ScriptBlock $pip_install -Arg '-msg "py2exe 0.6.9" -mod "py2exe_py2==0.6.9" -script_dir $PythonScripts'
        $job9 = Start-Job -ScriptBlock $pip_install -Arg '-msg "pycrypto 2.6.1" -mod "pycrypto==2.6.1" -script_dir $PythonScripts'
        $job10 = Start-Job -ScriptBlock $pip_install -Arg '-msg "comtypes 1.1.3" -mod "https://github.com/enthought/comtypes/archive/1.1.3.zip" -script_dir $PythonScripts'
        $job11 = Start-Job -ScriptBlock $pip_install -Arg '-msg "ctypeslib 0.5.6" -mod "svn+http://svn.python.org/projects/ctypes/trunk/ctypeslib/#ctypeslib=0.5.6" -script_dir $PythonScripts'
        $job12 = Start-Job -ScriptBlock $pip_install -Arg '-msg "paramiko 2.2.1" -mod "paramiko==2.2.1" -script_dir $PythonScripts'
        $job13 = Start-Job -ScriptBlock $pip_install -Arg '-msg "pywin32 223" -mod "pywin32==223" -script_dir $PythonScripts'

        $jobs = ($job1, $job2, $job3, $job4, $job5, $job6, $job7, $job8, $job9, $job10, $job11, $job12, $job13)
        Get-Job
        ForEach($job in $jobs) {
          if ($job.HasMoreData) {
            Receive-Job $job
            Get-Job
          }
        }
        Wait-Job
      }

      " "
      "--- pywin32 post install"
      $PywinPostInstall = $PythonScripts +"\pywin32_postinstall.py"
      Start-Process python -Arg "$PywinPostInstall -install -silent -quiet" -Wait
      "    Done."
      #" "
      #"--- Inno Setup 5.5.9"
      #$InnoInstaller = $InstallersFolder + "innosetup-5.5.9-unicode.exe"
      #$InnoURL = "http://files.jrsoftware.org/is/5/innosetup-5.5.9-unicode.exe"
      #Start-FileDownload $InnoURL -Timeout 60000 -FileName $InnoInstaller | ForEach-Object { Write-Host "    " + $_ }
      #"    Installing..."
      #Start-Process $InnoInstaller -Arg "/SP /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /RESTARTAPPLICATIONS /NOICONS" -NoNewWindow -Wait
      #"    Done."
      " "
      " "
      "=============== start the EventGhost build ==============="
      " "
      If ($Env:APPVEYOR_REPO_TAG.tolower() -eq "true" -and
        $Env:APPVEYOR_REPO_TAG_NAME.tolower().startswith("deploy"))
      {
        # to do a release, create a tag in the form "Deploy_VERSION"
        # VERSION must be a valid version string (without leading 'v')
        # this tag will be deleted and a new release "vVERSION" created.
        git checkout -q master
        $release = $Env:APPVEYOR_REPO_TAG_NAME.split("_", 2)[1]
        $url = if($Env:SFTP_URL){' --docs --url "' + $env:SFTP_URL + '"'} else {''}
        python "_build\Build.py" --build --package --release --version $release $url
      } Else {
        # WIP
        python "_build\Build.py" --build --package
        .\EventGhost.exe -install
      }
      $Env:SetupExe = gci -recurse -filter "_build\output\*Setup.exe" -name

      # update the appveyor build version to be the same as the EventGhost version
      $start = $env:SetupExe.IndexOf("_")
      $length = $env:SetupExe.LastIndexOf("_") - $start
      $build_version = $env:SetupExe.Substring($start + 1, $length - 1)
      Update-AppveyorBuild -Version "$build_version"

      # Make sure the appveyor cache is only saved if our build was successfull
      If (-Not (Test-Path(".\EventGhost.exe"))) {$env:APPVEYOR_CACHE_SKIP_SAVE = "true"}

      " "

      "=============== EventGhost build finished ==============="
      " "
      " "


build:
  off
  # If we don't turn build off, we get an error from appveyor telling us,
  # we should decide, which project or solution file to use, because the
  # folder contains more than one project or solution file.
  # We don't really "build" (with a compiler), but Appveyor finds the
  # solution files in the extension sub-directories and complains.


#after_test:
#  - cmd:  echo "=============== EventGhost build finished ==============="
#  # - cmd: START /WAIT %setup-exe% /VERYSILENT /SUPPRESSMSGBOXES /NOCLOSEAPPLICATIONS


artifacts:
  - path: _build\output\$(SetupExe)
    name: $(SetupExe)
  - path: _build\output\Build.log
    name: Build.log
  - path: _build\output\CHANGELOG.md
    name: CHANGELOG.md
  - path: _build\output\CHANGELOG_THIS_RELEASE.md
    name: CHANGELOG_THIS_RELEASE.md
  - path: _build\output\CHANGELOG_THIS_RELEASE.bb
    name: CHANGELOG_THIS_RELEASE.bb


notifications:
- provider: GitHubPullRequest
  template: >-
    [{{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}})

    Artifacts:

    {{#jobs}}
    {{#artifacts}}
    [{{name}}]({{permalink}})

    {{/artifacts}}
    {{/jobs}}

  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

- provider: Slack
  incoming_webhook:
    secure: DXo21MuJufndeGjaRDMxLgLo5yEaPf9uYg1YqrHPlfjsXUAzxRR2yGhCKcUwfLTT3gO192GKwkNAc52Y6TnxuKsNAgI+K5mBW40+6I9FOmU=

  template: >-
    <{{buildUrl}}|{{projectName}} {{buildVersion}} {{status}}>

    Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}:

    Commit message: _{{commitMessage}}_


    Artifacts:

    {{#jobs}}{{#artifacts}}<{{permalink}}|{{name}}>

    {{/artifacts}}{{/jobs}}

  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true



#on_finish:
#  # Enable Remotedesktop and pause the build execution
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


# notifications:
#   - provider: GitHubPullRequest
#     template: "{{#passed}}:white_check_mark: [Setup.exe](https://ci.appveyor.com/api/buildjobs/$(APPVEYOR_JOB_ID)/artifacts/_build%2Foutput%2F$(setup-exe)){{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
