test= {
    "placements":{
        "PanelUI-contents":[
            "edit-controls",
            "zoom-controls",
            "new-window-button",
            "privatebrowsing-button",
            "save-page-button",
            "print-button",
            "history-panelmenu",
            "fullscreen-button",
            "find-button",
            "preferences-button",
            "add-ons-button",
            "developer-button",
            "sync-button"
        ],
        "addon-bar":[
            "addonbar-closebutton",
            "status-bar"
        ],
        "PersonalToolbar":[
            "personal-bookmarks"
        ],
        "nav-bar":[
            "urlbar-container",
            "search-container",
            "bookmarks-menu-button",
            "pocket-button",
            "home-button",
            "loop-button",
            "statusbar-translator",
            "abp-toolbarbutton",
            "ublock0-button",
            "downloads-button",
            "_76ccdfe4-8932-4343-a4a7-bf79c2543558_-browser-action",
            "guiconfig-open-preferences"
        ],
        "TabsToolbar":[
            "tabbrowser-tabs",
            "new-tab-button",
            "alltabs-button"
        ],
        "toolbar-menubar":[
            "menubar-items"]},"seen":[
            "abp-toolbarbutton",
            "ublock0-button",
            "_76ccdfe4-8932-4343-a4a7-bf79c2543558_-browser-action",
            "pocket-button",
            "developer-button",
            "guiconfig-open-preferences"
        ],
        "dirtyAreaCache":[
            "PersonalToolbar",
            "nav-bar",
            "TabsToolbar",
            "toolbar-menubar",
            "PanelUI-contents",
            "addon-bar"
        ],
        "currentVersion":6,"newElementCount":0}
